import { supabaseAdmin } from "@/lib/supabase";
import { AGENCIES, KAKAO_URL, BUSINESS_CARD_LINK_URL } from "@/lib/agencies";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// 기존 정적 manifest.js와 동일한 형태로 응답.
// 모아보기/키워드 페이지의 기존 코드가 window.MIH를 그대로 사용 가능.
export async function GET() {
  const sb = supabaseAdmin();
  const { data, error } = await sb
    .from("articles")
    .select("id, publish_date, agency, slug, title, html_content, source_path")
    .order("publish_date", { ascending: false })
    .order("slug", { ascending: true });

  if (error) {
    return new Response(`/* DB error: ${error.message} */\nwindow.MIH = null;\n`, {
      headers: { "Content-Type": "application/javascript; charset=utf-8" },
      status: 500,
    });
  }

  const manuscripts = (data || []).map((r) => ({
    id: r.id,
    path: r.source_path || `${r.publish_date}/${r.agency}/${r.slug}.html`,
    agency: r.agency,
    slug: r.slug,
    title: r.title,
    date: r.publish_date,
    html: r.html_content,
  }));

  const payload = {
    generatedAt: new Date().toISOString(),
    kakaoUrl: KAKAO_URL,
    businessCardLinkUrl: BUSINESS_CARD_LINK_URL,
    agencies: AGENCIES,
    manuscripts,
  };

  const body =
    "// AUTO-GENERATED by /api/manifest.js — DB-backed\n" +
    "window.MIH = " +
    JSON.stringify(payload) +
    ";\n";

  return new Response(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
